baseURL = 'https://migibert.github.io/'
languageCode = 'en-us'
title = "Mikaël Gibert"
theme = 'PaperMod'
showSearch = true
description = "Mikaël Gibert's personal space, let's explore System Thinking and Theory of Constraints!"

[[menu.main]]
identifier = 'distributed-systems'
name = 'Distributed Systems'
url = '/categories/distributed-systems/'
weight = 10

[[menu.main]]
identifier = 'management'
name = 'Management'
url = '/categories/management/'
weight = 20

[[menu.main]]
identifier = 'toc'
name = 'Theory of Constraints'
url = '/categories/theory-of-constraints/'
weight = 30

[[menu.main]]
identifier = 'se'
name = 'Software Engineering'
url = '/categories/software-engineering/'
weight = 40

[[menu.main]]
identifier = 'creations'
name = 'Creations'
url = '/creations/'
weight = 1 

[[menu.main]]
identifier = "search"
name = ""
url = "search/"
weight = 100
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><circle cx="10" cy="10" r="7" fill="none" stroke="currentColor" stroke-width="2"/><line x1="15.5" y1="15.5" x2="22" y2="22" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'

[params]
ShowShareButtons = true
ShareButtons = ['linkedin', 'x', 'facebook', 'reddit']
author = "Mikaël Gibert"

[params.homeInfoParams]
Title = "Welcome!"
Content = """
  I'm an engineer passionate about DevOps, System Design, and Flow.

  Inspired by The Phoenix Project, I love exploring constraints, causality, and efficiency to create better systems... and a better world!

  Outside of tech, I enjoy gardening, martial arts, guitar, cooking, and writing. Let's connect!
"""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/migibert"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mikael-gibert/"

[[params.socialIcons]]
  name = "medium"
  url = "https://medium.com/@mikael.gibert"

[[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/6084892/mikael-gibert"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/migibert"

[outputs]
  home = ["HTML", "RSS", "JSON"]
